# PLEASE NOTE
# IDs in these requests must be changed as rooms/users are created/deleted

# Create User
POST https://in-sync-app-backend.herokuapp.com/user
Accept: application/json
content-type: application/json

{
    "email": "test2@test.com",
    "username": "TestMan2",
    "password": "testPass2"
}

###

# Get All Users
GET https://in-sync-app-backend.herokuapp.com/user
Accept: application/json

###

# Get User By Id
GET https://in-sync-app-backend.herokuapp.com/user/5ea8de31f4d4b92ac44db792
Accept: application/json

###

# Logging In
GET https://in-sync-app-backend.herokuapp.com/login
Accept: application/json
content-type: application/json

{
    "username": "TestMan",
    "password": "testPass"
}

###

# Create Room
POST https://in-sync-app-backend.herokuapp.com/room
Accept: application/json
content-type: application/json

{
    "host": "5ea8de31f4d4b92ac44db792",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "viewers": []
}

###

# Get Room By Id
GET https://in-sync-app-backend.herokuapp.com/room/5ea8e0e8f4d4b92ac44db797
Accept: application/json

###

# Get All Rooms
GET https://in-sync-app-backend.herokuapp.com/room
Accept: application/json

###

# Join Room
PUT https://in-sync-app-backend.herokuapp.com/room
Accept: application/json
content-type: application/json

{
    "userId": "5ea8e204f4d4b92ac44db798",
    "id": "5ea8e0e8f4d4b92ac44db797"
}

###

# Update Room
PUT https://in-sync-app-backend.herokuapp.com/room/5ea8e0e8f4d4b92ac44db797
Accept: application/json
content-type: application/json

{
    "video": "https://www.youtube.com/watch?v=2Jvvz8n_hZ0"
}

###

# Delete Room
DELETE https://in-sync-app-backend.herokuapp.com/room/5ea8e376f4d4b92ac44db799
Accept: application/json

###
